import './LegalPage.css';

export default function Disclaimer() {
  return (
    <div className="legal-page">
      <a href="#/overview" className="legal-back-link">&larr; Back to MarketMind</a>

      <div className="legal-header">
        <h1>Disclaimer</h1>
        <div className="legal-meta">
          <span>Last updated: March 27, 2026</span>
          <span className="legal-version-badge">Version 1.0</span>
        </div>
      </div>

      <div className="legal-highlight">
        <strong>IMPORTANT: Please read this Disclaimer carefully before using MarketMind.</strong> This platform is an academic project for educational purposes only. Nothing on this platform constitutes financial advice, investment advice, trading advice, or any other form of professional advice. All trading activity on this platform is simulated with fictional currency.
      </div>

      <nav className="legal-toc">
        <h3>Table of Contents</h3>
        <ol>
          <li><a href="#disc-educational">Educational Purpose Only</a></li>
          <li><a href="#disc-not-advice">Not Financial Advice</a></li>
          <li><a href="#disc-simulation">Paper Trading Simulation</a></li>
          <li><a href="#disc-ml">ML Prediction Accuracy</a></li>
          <li><a href="#disc-third-party">Third-Party Data</a></li>
          <li><a href="#disc-no-liability">No Liability</a></li>
          <li><a href="#disc-professional">Consult a Professional</a></li>
        </ol>
      </nav>

      <section className="legal-section" id="disc-educational">
        <h2>1. Educational Purpose Only</h2>
        <p>MarketMind is an academic Final Year Project. The platform was created solely for academic and educational purposes to demonstrate the application of machine learning techniques to financial data analysis.</p>
        <p>The platform is designed to help users learn about:</p>
        <ul>
          <li>How stock markets operate.</li>
          <li>Basic and advanced trading concepts.</li>
          <li>How machine learning models can be applied to financial data.</li>
          <li>Technical analysis indicators and their interpretation.</li>
          <li>Portfolio management theory (e.g., Markowitz optimisation).</li>
          <li>Sentiment analysis of financial news and social media.</li>
        </ul>
        <p><strong>This platform is not a commercial product, financial service, or investment tool.</strong></p>
      </section>

      <section className="legal-section" id="disc-not-advice">
        <h2>2. Not Financial Advice</h2>
        <div className="legal-highlight">
          <strong>Nothing on this platform — including but not limited to ML predictions, confidence scores, buy/sell signals, sentiment analyses, research briefs, portfolio optimisation results, backtesting results, and educational content — constitutes financial advice, investment advice, tax advice, legal advice, or any other form of professional advice.</strong>
        </div>
        <p>The information provided on this platform is for general educational and informational purposes only. It should not be relied upon as a basis for making any real-world financial or investment decisions.</p>
        <p>We are not registered with, regulated by, or affiliated with any financial regulatory authority, including but not limited to the Central Bank of Ireland, the U.S. Securities and Exchange Commission (SEC), the Financial Industry Regulatory Authority (FINRA), or any equivalent body in any jurisdiction.</p>
      </section>

      <section className="legal-section" id="disc-simulation">
        <h2>3. Paper Trading Simulation</h2>
        <p>All trading activity on MarketMind is conducted in a <strong>simulated environment using fictional virtual currency</strong>. Specifically:</p>
        <ul>
          <li>No real money is deposited, invested, transferred, or at risk at any time.</li>
          <li>Virtual portfolio balances (e.g., the initial $100,000) have no real-world monetary value.</li>
          <li>Simulated trades do not execute on any real stock exchange or brokerage.</li>
          <li>Virtual profits and losses do not represent real financial outcomes.</li>
          <li>Performance metrics, returns, and portfolio values are entirely fictional.</li>
          <li>Simulated trading results cannot be redeemed, withdrawn, or exchanged for real currency, goods, or services.</li>
        </ul>
        <p>Simulated trading performance is not indicative of real-world trading results. Real trading involves significant risks including the potential loss of your entire investment.</p>
      </section>

      <section className="legal-section" id="disc-ml">
        <h2>4. ML Prediction Accuracy</h2>
        <p>The machine learning predictions displayed on this platform are generated by academic ensemble models (Random Forest, Gradient Boosting, XGBoost) trained on historical market data. These predictions are subject to significant limitations:</p>
        <ul>
          <li><strong>Past performance does not guarantee future results.</strong> Historical accuracy metrics do not predict future prediction accuracy.</li>
          <li>Models are trained on historical data and may not account for unprecedented market events, black swan events, or regime changes.</li>
          <li>Confidence scores are calibrated estimates, not guarantees of accuracy.</li>
          <li>Sentiment analysis is based on automated natural language processing and may misinterpret context, sarcasm, or nuance.</li>
          <li>Technical indicators are mathematical calculations based on historical prices and do not predict future price movements with certainty.</li>
          <li>Backtesting results are hypothetical and subject to look-ahead bias, survivorship bias, and other methodological limitations.</li>
          <li>The Fear &amp; Greed Index is a custom composite metric and does not represent an official market indicator.</li>
        </ul>
        <p><strong>ML predictions are academic demonstrations and must not be used as the basis for real investment decisions.</strong></p>
      </section>

      <section className="legal-section" id="disc-third-party">
        <h2>5. Third-Party Data</h2>
        <p>MarketMind displays market data, news articles, and other information sourced from third-party providers including Finnhub, Yahoo Finance, NewsAPI, and Reddit. We do not guarantee the accuracy, completeness, timeliness, or reliability of any third-party data.</p>
        <ul>
          <li>Stock prices may be delayed or inaccurate.</li>
          <li>News articles are sourced automatically and may contain errors or biased information.</li>
          <li>Reddit sentiment data reflects user-generated content and may not represent informed or accurate market analysis.</li>
          <li>Historical data may contain gaps, errors, or adjustments that affect calculation accuracy.</li>
        </ul>
        <p>Third-party content and data displayed on the platform are subject to the respective providers' own terms and conditions. We are not responsible for any third-party content.</p>
      </section>

      <section className="legal-section" id="disc-no-liability">
        <h2>6. No Liability</h2>
        <div className="legal-highlight">
          <strong>MarketMind, its developer, and academic supervisors accept no liability whatsoever for any loss, damage, or expense — whether direct, indirect, incidental, consequential, or otherwise — arising from or in connection with:</strong>
        </div>
        <ul>
          <li>Your use of or reliance on any information, prediction, analysis, or data provided by the Service.</li>
          <li>Any real-world financial, investment, or trading decision made by you, regardless of whether such decision was influenced by or related to the Service.</li>
          <li>Any errors, omissions, or inaccuracies in the data or predictions displayed on the platform.</li>
          <li>Any interruption, suspension, or termination of the Service.</li>
          <li>Any unauthorised access to your account or data.</li>
        </ul>
        <p>You use this platform entirely at your own risk and accept full responsibility for any consequences arising from your use of or reliance on the Service.</p>
      </section>

      <section className="legal-section" id="disc-professional">
        <h2>7. Consult a Professional</h2>
        <p>If you are considering making real-world financial or investment decisions, we strongly recommend that you:</p>
        <ul>
          <li>Consult with a qualified, licensed financial adviser or investment professional.</li>
          <li>Consult with a qualified tax adviser regarding tax implications.</li>
          <li>Conduct your own thorough research and due diligence.</li>
          <li>Understand the risks associated with investing and trading, including the risk of losing your entire investment.</li>
          <li>Never invest money that you cannot afford to lose.</li>
        </ul>
        <p>Remember: <strong>MarketMind is an educational tool, not an investment platform.</strong> The simulated environment is designed to help you learn, not to guide real financial decisions.</p>
      </section>
    </div>
  );
}
