import './LegalPage.css';

export default function TermsOfService() {
  return (
    <div className="legal-page">
      <a href="#/overview" className="legal-back-link">&larr; Back to MarketMind</a>

      <div className="legal-header">
        <h1>Terms of Service</h1>
        <div className="legal-meta">
          <span>Last updated: March 27, 2026</span>
          <span className="legal-version-badge">Version 1.0</span>
        </div>
      </div>

      <div className="legal-highlight">
        <strong>Important:</strong> MarketMind is an academic project and educational platform. It provides a <strong>simulated paper trading environment only</strong>. No real money, real securities, or real brokerage services are involved. By using this platform, you acknowledge that all trading activity is fictional and for educational purposes only.
      </div>

      <nav className="legal-toc">
        <h3>Table of Contents</h3>
        <ol>
          <li><a href="#tos-acceptance">Acceptance of Terms</a></li>
          <li><a href="#tos-description">Platform Description</a></li>
          <li><a href="#tos-eligibility">Eligibility</a></li>
          <li><a href="#tos-accounts">Account Terms</a></li>
          <li><a href="#tos-acceptable-use">Acceptable Use</a></li>
          <li><a href="#tos-ip">Intellectual Property</a></li>
          <li><a href="#tos-disclaimer">Disclaimer of Warranties</a></li>
          <li><a href="#tos-liability">Limitation of Liability</a></li>
          <li><a href="#tos-indemnification">Indemnification</a></li>
          <li><a href="#tos-termination">Termination</a></li>
          <li><a href="#tos-governing">Governing Law</a></li>
          <li><a href="#tos-modifications">Modifications</a></li>
          <li><a href="#tos-contact">Contact Information</a></li>
        </ol>
      </nav>

      <section className="legal-section" id="tos-acceptance">
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing or using the MarketMind platform ("Service"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to all of these Terms, you must not access or use the Service.</p>
        <p>These Terms constitute a legally binding agreement between you ("User", "you") and MarketMind ("we", "us", "our"), an academic Final Year Project.</p>
        <p>By creating an account, you represent that you have read, understood, and agree to be bound by these Terms, as well as our <a href="#/privacy">Privacy Policy</a>, <a href="#/disclaimer">Disclaimer</a>, <a href="#/acceptable-use">Acceptable Use Policy</a>, and <a href="#/cookie-policy">Cookie Policy</a>, all of which are incorporated by reference into these Terms.</p>
      </section>

      <section className="legal-section" id="tos-description">
        <h2>2. Platform Description</h2>
        <p>MarketMind is an educational, academic project that provides:</p>
        <ul>
          <li><strong>Simulated paper trading</strong> — All trades are executed with virtual (fictional) currency. No real money is deposited, invested, transferred, or at risk at any time.</li>
          <li><strong>Machine learning-based price predictions</strong> — Generated by academic ensemble models for educational demonstration purposes only. These predictions are not financial advice and should not be relied upon for real investment decisions.</li>
          <li><strong>Market data aggregation</strong> — Stock prices, news, and sentiment data sourced from third-party APIs (Finnhub, Yahoo Finance, NewsAPI, Reddit) for educational display purposes.</li>
          <li><strong>Educational content</strong> — Interactive lessons and quizzes about stock markets, trading concepts, and machine learning.</li>
        </ul>
        <p>MarketMind is <strong>not</strong> a registered broker-dealer, investment adviser, financial institution, or money services business. The Service does not facilitate real securities transactions of any kind.</p>
      </section>

      <section className="legal-section" id="tos-eligibility">
        <h2>3. Eligibility</h2>
        <p>To use this Service, you must:</p>
        <ul>
          <li>Be at least 18 years of age, or at least 13 years of age with verifiable parental or guardian consent.</li>
          <li>Have the legal capacity to enter into a binding agreement.</li>
          <li>Not be prohibited from using the Service under any applicable law or regulation.</li>
        </ul>
        <p>By creating an account, you represent and warrant that you meet all eligibility requirements. If you are under 18, you represent that your parent or legal guardian has reviewed and agreed to these Terms on your behalf.</p>
      </section>

      <section className="legal-section" id="tos-accounts">
        <h2>4. Account Terms</h2>
        <h3>4.1 Account Registration</h3>
        <p>You must provide a valid email address and create a secure password to register for an account. You agree to provide accurate and complete information during registration and to keep your account information up to date.</p>
        <h3>4.2 Account Security</h3>
        <p>You are solely responsible for maintaining the confidentiality of your account credentials. You must immediately notify us of any unauthorised access to or use of your account. We are not liable for any loss or damage arising from your failure to protect your account credentials.</p>
        <h3>4.3 One Account Per User</h3>
        <p>Each user may maintain only one account. Creating multiple accounts to manipulate simulated trading results, exploit platform features, or circumvent any restrictions is strictly prohibited.</p>
        <h3>4.4 Account Data</h3>
        <p>Your simulated portfolio, trade history, and learning progress are stored on our servers. Virtual balances and positions have no real-world monetary value and cannot be redeemed, transferred, or exchanged for real currency, goods, or services.</p>
      </section>

      <section className="legal-section" id="tos-acceptable-use">
        <h2>5. Acceptable Use</h2>
        <p>Your use of the Service is subject to our <a href="#/acceptable-use">Acceptable Use Policy</a>, which is incorporated into these Terms by reference. You agree not to misuse the Service in any manner that could damage, disable, overburden, or impair it, or interfere with any other party's use of the Service.</p>
      </section>

      <section className="legal-section" id="tos-ip">
        <h2>6. Intellectual Property</h2>
        <h3>6.1 Our Property</h3>
        <p>The Service, including its original content, features, functionality, source code, machine learning models, design, and branding, is and remains the exclusive property of MarketMind and its developer. The Service is protected by copyright, trademark, and other intellectual property laws of Ireland and international conventions.</p>
        <h3>6.2 Your Data</h3>
        <p>You retain ownership of any personal data you provide to us (such as your display name and email). By using the Service, you grant us a limited licence to process this data solely for the purpose of providing the Service to you, as described in our <a href="#/privacy">Privacy Policy</a>.</p>
        <h3>6.3 Feedback</h3>
        <p>Any feedback, suggestions, or ideas you voluntarily provide regarding the Service may be used by us without any obligation to you.</p>
      </section>

      <section className="legal-section" id="tos-disclaimer">
        <h2>7. Disclaimer of Warranties</h2>
        <div className="legal-highlight">
          <strong>THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE.</strong> We expressly disclaim all warranties, including but not limited to implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement.
        </div>
        <p>Without limiting the foregoing, we make no warranty or representation that:</p>
        <ul>
          <li>The Service will meet your requirements or expectations.</li>
          <li>The Service will be uninterrupted, timely, secure, or error-free.</li>
          <li>Any machine learning predictions, confidence scores, or sentiment analyses will be accurate, reliable, or profitable.</li>
          <li>Any market data, stock prices, or financial information displayed on the platform will be accurate, complete, or current.</li>
          <li>Any results obtained from using the Service will be accurate or reliable.</li>
          <li>Any errors or defects in the Service will be corrected.</li>
        </ul>
      </section>

      <section className="legal-section" id="tos-liability">
        <h2>8. Limitation of Liability</h2>
        <div className="legal-highlight">
          <strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL MARKETMIND, ITS DEVELOPER, AFFILIATES, SUPERVISORS, OR THE HOST EDUCATIONAL INSTITUTION BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO:</strong>
        </div>
        <ul>
          <li>Loss of profits, revenue, data, goodwill, or other intangible losses.</li>
          <li>Any damages arising from your use of or inability to use the Service.</li>
          <li>Any damages arising from any financial, investment, or trading decisions made based on or influenced by information, predictions, analyses, or data displayed on or generated by the Service.</li>
          <li>Any damages arising from unauthorised access to or alteration of your transmissions or data.</li>
          <li>Any damages arising from third-party content, services, or conduct on or through the Service.</li>
        </ul>
        <p><strong>In no event shall our total aggregate liability exceed zero euros (EUR 0.00), reflecting the free, non-commercial, academic nature of this Service.</strong></p>
        <p>You expressly acknowledge and agree that this platform is a student academic project and not a commercial product. You use the Service entirely at your own risk.</p>
      </section>

      <section className="legal-section" id="tos-indemnification">
        <h2>9. Indemnification</h2>
        <p>You agree to defend, indemnify, and hold harmless MarketMind, its developer, and academic supervisors from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including reasonable legal fees) arising from:</p>
        <ul>
          <li>Your use of and access to the Service.</li>
          <li>Your violation of any provision of these Terms.</li>
          <li>Your violation of any third-party right, including any intellectual property, privacy, or proprietary right.</li>
          <li>Any claim that your use of the Service caused damage to a third party.</li>
          <li>Any real-world financial, investment, or trading decision you make that was in any way informed by or related to the Service.</li>
        </ul>
        <p>This defence and indemnification obligation will survive termination of these Terms and your use of the Service.</p>
      </section>

      <section className="legal-section" id="tos-termination">
        <h2>10. Termination</h2>
        <p>We may terminate or suspend your account and access to the Service immediately, without prior notice or liability, for any reason, including without limitation if you breach these Terms.</p>
        <p>You may terminate your account at any time by using the account deletion feature in your <a href="#/settings">Settings</a> page. Upon termination, your right to use the Service will immediately cease.</p>
        <p>All provisions of these Terms which by their nature should survive termination shall survive, including without limitation ownership provisions, warranty disclaimers, indemnification, and limitations of liability.</p>
      </section>

      <section className="legal-section" id="tos-governing">
        <h2>11. Governing Law</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of Ireland, without regard to its conflict of law provisions.</p>
        <p>Any disputes arising out of or in connection with these Terms or the Service shall be subject to the exclusive jurisdiction of the courts of Ireland.</p>
        <p>Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights.</p>
      </section>

      <section className="legal-section" id="tos-modifications">
        <h2>12. Modifications to Terms</h2>
        <p>We reserve the right to modify or replace these Terms at any time at our sole discretion. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect, by posting a notice on the platform or updating the "Last updated" date at the top of these Terms.</p>
        <p>Your continued use of the Service after any such changes constitutes your acceptance of the new Terms. If you do not agree to the new Terms, you must stop using the Service.</p>
      </section>

      <section className="legal-section" id="tos-contact">
        <h2>13. Contact Information</h2>
        <p>If you have any questions about these Terms, please contact us:</p>
        <div className="legal-contact-card">
          <p><strong>MarketMind</strong></p>
          <p>Email: <a href="mailto:support@marketmind.cfd">support@marketmind.cfd</a></p>
        </div>
      </section>
    </div>
  );
}
